### ISSUE TITLE
About generate_smaps.py

### ISSUE THREAD

**Issue by Breeze-Zero** [Aboriginer/HFS-SDE#1]
https://github.com/Aboriginer/HFS-SDE/blob/197725c1dd7c10d0e5500371649091c174d13737/data_prepare/generate_smaps.py#L45-L50
I'm a little unsure about the bart internal input requirements, but here it seems to be a sens map of slice 0 each time

**Comment by Aboriginer** [comment]
Hi Breeze,

Thanks for pointing out our error. We have fixed the code now.

The bart internal input requirements: [slice, kx, ky, NC]

Additionally, you may need the code for estimating maps on fastMRI data, you can find it [here](https://github.com/Aboriginer/HFS-SDE/blob/master/data_prepare/generate_smaps_fastMRI.py).
