### ISSUE TITLE
About the data preprocess

### ISSUE THREAD

**Issue by Ashliquid** [Aboriginer/HFS-SDE#3]
Is your algorithm sensitive to data preprocessing methods? I did the min-max normalization and the results were not ideal.
I retrained the diffusion model in the algorithm on your weights file.

**Comment by Aboriginer** [comment]
Hi @Ashliquid, sorry for the late reply. 

If you change the normalization, I think you should tune hyperparameters (sampling.snr, sampling.mse, and sampling.corrector_mse) during the inference time to achieve better results.
