### ISSUE TITLE
Adapting preprocessing to chest x-ray images

### ISSUE THREAD

**Issue by drainvers** [Aboriginer/HFS-SDE#5]
Hi, how would the preprocessing method be adapted to x-ray images? Do they require sensitivity maps like MRIs would? For context, I am currently attempting to reproduce this paper and adapting it to work on the CheXpert dataset.

**Comment by Aboriginer** [comment]
Hi @drainvers, thanks for your interest in our work, but I don't know much about X-ray imaging. As far as I know, X-ray imaging does not require coil sensitivity.
